version: '3.8'
services:
  # postgres://prisma:prisma@localhost:5700
  postgres:
    image: postgres:15
    container_name: nexus-prisma-test
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5700:5432'
