name: docs-trunk

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn --frozen-lockfile
      - run: yarn -s build
      - run: yarn -s export
      - run: gh-pages --dist=out
