name: docs-pr

on:
  pull_request:
    paths:
      - docs/**

defaults:
  run:
    working-directory: docs

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s format:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s lint:check
