name: pr

on:
  - pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s format:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s lint:check

  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn global add yalc
      - run: yarn --frozen-lockfile
      - name: Set E2E DB Schema
        run: >
          E2E_DB_SCHEMA=$(yarn -s ts-node scripts/get-e2e-db-schema --os ${{ matrix.os }} --node-version ${{ matrix.node-version }})
          echo "E2E_DB_SCHEMA=${E2E_DB_SCHEMA}" >> $GITHUB_ENV
      - run: yarn -s build
      - run: yarn -s test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '12.x'
        with:
          directory: ./coverage
