name: pr

on:
  - pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s format:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s lint:check

  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres
        env:
          # https://hub.docker.com/_/postgres
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5700:5432
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn global add yalc
      - run: yarn --frozen-lockfile
      - run: yarn -s build
      - run: yarn -s test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '12.x'
        with:
          directory: ./coverage
