on:
  workflow_call:

jobs:
  test-latest-prisma-without-database:
    name: Test with latest Prisma
    timeout-minutes: 40

    strategy:
      matrix:
        os: ['macos-latest', 'windows-latest']
        node-version: [14, 16, 18]
        database: ['no-db']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Set E2E DB Schema for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: yarn -s ts-node scripts/get-e2e-db-schema --os ${{ matrix.os }} --node-version ${{ matrix.node-version }} --github-env $env:GITHUB_ENV

      - name: Set E2E DB Schema for other operating systems
        if: ${{ matrix.os != 'windows-latest' }}
        run: yarn -s ts-node scripts/get-e2e-db-schema --os ${{ matrix.os }} --node-version ${{ matrix.node-version }} --github-env $GITHUB_ENV

      - name: Build
        run: yarn -s build

      - name: Test
        run: yarn -s test:ci
        env:
          DATABASE: ${{ matrix.database }}

  test-latest-prisma-with-database:
    name: Test with latest Prisma
    timeout-minutes: 40

    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [14, 16, 18]
        database: ['db']

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Set E2E DB Schema for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: yarn -s ts-node scripts/get-e2e-db-schema --os ${{ matrix.os }} --node-version ${{ matrix.node-version }} --github-env $env:GITHUB_ENV

      - name: Set E2E DB Schema for other operating systems
        if: ${{ matrix.os != 'windows-latest' }}
        run: yarn -s ts-node scripts/get-e2e-db-schema --os ${{ matrix.os }} --node-version ${{ matrix.node-version }} --github-env $GITHUB_ENV

      - name: Build
        run: yarn -s build

      - name: Test
        run: yarn -s test:ci
        env:
          DATABASE: ${{ matrix.database }}

  test-past-versions-with-database:
    name: Test with past versions
    timeout-minutes: 40

    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [18]
        database: ['db']
        past-version: ['prisma@4.0, graphql@15.8.0', 'graphql@15.8.0']

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn -s build

      - name: Set E2E DB Schema
        if: contains(matrix.past-version, 'prisma')
        run: yarn -s ts-node scripts/get-e2e-db-schema --os ${{ matrix.os }} --node-version ${{ matrix.node-version }} --prisma-client-version 4.0 --github-env $GITHUB_ENV

      - name: Set E2E DB Schema
        if: contains(matrix.past-version, 'prisma') == false
        run: yarn -s ts-node scripts/get-e2e-db-schema --os ${{ matrix.os }} --node-version ${{ matrix.node-version }} --github-env $GITHUB_ENV

      - name: Install past prisma dev packages
        if: contains(matrix.past-version, 'prisma')
        run: yarn -s add prisma@4.0 @prisma/client@4.0 @prisma/internals@4.0 --dev

      - name: Install past prisma packages
        if: contains(matrix.past-version, 'prisma')
        run: yarn -s add @prisma/generator-helper@4.0

      - name: Install past graphql packages
        if: contains(matrix.past-version, 'graphql')
        run: yarn -s add graphql@^15.8.0 nexus@1.2 --dev

      - name: Test
        run: yarn -s test:ci
        env:
          DATABASE: ${{ matrix.database }}
          PAST_VERSION: ${{ matrix.past-version }}
