on:
  workflow_call:

jobs:
  validate:
    name: Validate Codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get lts node versions
        id: get-lts-versions
        run: scripts/get-lts-versions.sh

      - name: Use Node.js ${{ steps.get-lts-versions.outputs.last_lts_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-lts-versions.outputs.last_lts_version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run prettier
        run: yarn -s format

      - name: Run eslint
        run: yarn -s lint
